# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Payments • Thibault Milan
email: billing@thibaultmilan.com
description: All the services offered as a freelance from Thibault can be ordered here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site
twitter: https://twitter.com/thibaultmilan
github:  https://github.com/clawfire
facebook : https://www.facebook.com/thibault.milan.1

author : Thibault Milan

# Build settings
markdown: kramdown

collections:
  - offers
